#!/usr/bin/env bash
helptext="USAGE:     ${0##*/} FILE.md [FILE2.md ...]
WTF:       Converts markdown file(s) to temporary html and opens it for reading.
"

set -eo pipefail

#shellcheck source=../.qfuncs.sh
. ~/.qfuncs.sh


parse_args() {
   args=()
   dry_run=false

   while [ $# -gt 0 ]; do
      case "$1" in
      -h | --help)
         echo "$helptext" >&2
         exit
         ;;
      *)
         args+=("$1")
         ;;
      esac
      shift
   done
}

# shopt -s dotglob lastpipe  # add if as required

# functions go here
do_something() {
   declare -p FUNCNAME
}

# Detect whether this file is being sourced or executed.
if (return 0 2>/dev/null); then
   _sourced=true
else
   _sourced=false
fi

_main() {
   for arg in "${args[@]}"; do
      do_something "$arg"
   done
}

if ! $_sourced; then
   parse_args "$@"
   _main "${args[@]}"
fi

unset _sourced
